In [26]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
def sigmoid_activation_function(x):
  return 1 / (1+np.exp(-x))

In [28]:
def relu_activation_function(x):
  return np.maximum(0, x)

In [29]:
def sigmoid_back(dA, x):
  sigmoid = sigmoid_activation_function(x)
  return dA*sigmoid*(1-sigmoid)

In [30]:
def relu_back(dA, x):
  dx = np.array(dA, copy =True)
  dx[x <= 0] = 0
  return dx

In [31]:
'a'+'2'

'a2'

In [32]:
np.random.randn(2, 1)

array([[-0.01349722],
       [-1.05771093]])

In [33]:
np.random.randn(2, 1)*0.01

array([[ 0.00822545],
       [-0.01220844]])

In [34]:
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [35]:
def initilaize_deep_parameters(layer_dimension):
  np.random.seed(42)
  parameters = {}
  L = len(layer_dimension)

  for i in range(1, L):
    parameters["W"+ str(i)] = np.random.randn(layer_dimension[i], layer_dimension[i-1])*0.01
    parameters["b"+ str(i)] = np.zeros((layer_dimension[i], 1))

  return parameters

In [36]:
initilaize_deep_parameters([2, 4, 4, 2])

{'W1': array([[ 0.00496714, -0.00138264],
        [ 0.00647689,  0.0152303 ],
        [-0.00234153, -0.00234137],
        [ 0.01579213,  0.00767435]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W2': array([[-0.00469474,  0.0054256 , -0.00463418, -0.0046573 ],
        [ 0.00241962, -0.0191328 , -0.01724918, -0.00562288],
        [-0.01012831,  0.00314247, -0.00908024, -0.01412304],
        [ 0.01465649, -0.00225776,  0.00067528, -0.01424748]]),
 'b2': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W3': array([[-0.00544383,  0.00110923, -0.01150994,  0.00375698],
        [-0.00600639, -0.00291694, -0.00601707,  0.01852278]]),
 'b3': array([[0.],
        [0.]])}

In [37]:
def linear_forward(previous_data, weight, bias):
  x = np.dot(weight, previous_data) + bias
  linear_data = (previous_data, weight, bias)
  return x, linear_data

In [38]:
def linear_activation_function(previous_a, weight, bias, activation):
  if activation == "sigmoid":
    x, linear_data = linear_forward(previous_a, weight, bias)
    update_data = sigmoid_activation_function(x)

  elif activation == "relu":
    x, linear_data = linear_forward(previous_a, weight, bias)
    update_data = relu_activation_function(x)

  history = (linear_data, x)
  return update_data, history

In [39]:
def model_forward(x, parameters, activation):
  histories = []
  dummy_data = x
  layer_len = len(parameters)//2

  for i in range(1, layer_len):
    previous_data = dummy_data
    dummy_data, history = linear_activation_function(previous_data, parameters["W"+ str(i)], parameters["b"+ str(i)], activation[i-1])
    histories.append(history)

  dummy_data_store, history = linear_activation_function(previous_data, parameters["W"+ str(layer_len)], parameters["b"+ str(layer_len)], activation[layer_len-1])
  histories.append(history)

  return dummy_data_store, histories

In [40]:
def compute_cost(dummy_data_store,test_data):
  measure = test_data.shape[1]
  cost = -np.sum(test_data*np.log(dummy_data_store) + (1 - test_data) * np.log(1-dummy_data_store)) / measure
  cost  = np.squeeze(cost)
  return cost